export enum ContactsActionsTypes {
  FETCH_CONTACTS_LIST = 'FETCH_CONTACTS_LIST',
  FETCH_CONTACTS_LIST_ERROR = 'FETCH_CONTACTS_LIST_ERROR',
  ADD_CONTACTS_LIST = 'ADD_CONTACTS_LIST',
  UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT'
}
